version: '2'
services:

  php:
    build:
      dockerfile: Dockerfile-fpm
      context: 'php'
    image: ${STACK_PHP_IMAGE}:${PHP_IMAGE_VERSION}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
    volumes:
      - ./test:/test
  php-nginx:
    build:
      dockerfile: Dockerfile-fpm-nginx
      context: 'nginx'
      args:
        - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
    image: ${STACK_PHP_IMAGE}-nginx:${PHP_IMAGE_VERSION}
    environment:
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}

  php-alpine:
    build:
      dockerfile: Dockerfile-fpm-alpine
      context: 'php'
      args:
        - PHP_IMAGE_VERSION=${PHP_IMAGE_VERSION}
    image: ${STACK_PHP_IMAGE}-alpine
    volumes:
      - ./test:/test
  php-alpine-nginx:
    build:
      dockerfile: Dockerfile-fpm-alpine-nginx
      context: 'nginx'
    image: ${STACK_PHP_IMAGE}-alpine-nginx
