version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile-fpm
      context: 'php-7.0'
      args:
        - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    image: ${STACK_PHP_IMAGE}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
  php-nginx:
    build:
      dockerfile: Dockerfile-fpm-nginx
      context: 'nginx'
    image: ${STACK_PHP_IMAGE}-nginx
    environment:
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
