version: '2'
services:
  php:
    build:
      dockerfile: 7.0/Dockerfile-fpm
      context: .
      args:
        - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    image: ${STACK_PHP_IMAGE}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
