version: '2'
services:
  php:
    build:
      dockerfile: Dockerfile-fpm
      context: '7.0'
      args:
        - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    image: ${STACK_PHP_IMAGE}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
